// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API06.Models;

public partial class Purchase
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CourseId { get; set; }

    public int? CouponId { get; set; }

    public decimal PricePaid { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime PurchasedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}