//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentComponent
    {
        public AssessmentComponent()
        {
            this.StudentScores = new HashSet<StudentScore>();
        }
    
        public int ComponentID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public string ComponentName { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual TeachingAssignment TeachingAssignment { get; set; }
        public virtual ICollection<StudentScore> StudentScores { get; set; }
    }
}
