//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.TeachingAssignments = new HashSet<TeachingAssignment>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> HomeroomTeacherID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<TeachingAssignment> TeachingAssignments { get; set; }
    }
}
