// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API06.Models;

public partial class Coupon
{
    public int Id { get; set; }

    public string Code { get; set; }

    public decimal DiscountPct { get; set; }

    public int Quota { get; set; }

    public DateTime ExpiryDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}