//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScore
    {
        public int ScoreID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual AssessmentComponent AssessmentComponent { get; set; }
        public virtual User User { get; set; }
    }
}
