//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsemkaSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachingAssignment
    {
        public TeachingAssignment()
        {
            this.AssessmentComponents = new HashSet<AssessmentComponent>();
        }
    
        public int AssignmentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual ICollection<AssessmentComponent> AssessmentComponents { get; set; }
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
