// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MBCA_API_04.Models;

public partial class Event
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly Date { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public string Location { get; set; }

    public string Initiator { get; set; }

    public decimal Price { get; set; }

    public int EventCategoryId { get; set; }

    public virtual ICollection<EventBanner> EventBanners { get; set; } = new List<EventBanner>();

    public virtual EventCategory EventCategory { get; set; }

    public virtual ICollection<EventExhibit> EventExhibits { get; set; } = new List<EventExhibit>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}