// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MBCA_API_04.Models;

public partial class EventExhibit
{
    public int Id { get; set; }

    public int EventId { get; set; }

    public int ExhibitId { get; set; }

    public virtual Event Event { get; set; }

    public virtual Exhibit Exhibit { get; set; }
}