// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MBCA_API_04.Models;

public partial class Otp
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Code { get; set; }

    public byte[] ValidUntil { get; set; }

    public virtual User User { get; set; }
}