//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventBanners = new HashSet<EventBanner>();
            this.EventExhibits = new HashSet<EventExhibit>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Location { get; set; }
        public string Initiator { get; set; }
        public decimal Price { get; set; }
        public int EventCategoryID { get; set; }
    
        public virtual EventCategory EventCategory { get; set; }
        public virtual ICollection<EventBanner> EventBanners { get; set; }
        public virtual ICollection<EventExhibit> EventExhibits { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
