//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.OTPs = new HashSet<OTP>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int RoleID { get; set; }
        public byte IsActivated { get; set; }
    
        public virtual ICollection<OTP> OTPs { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
