//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovSedhep
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantTable
    {
        public RestaurantTable()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int TableID { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
