// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MBCA_API_04.Models;

public partial class EventCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}