// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MBCA_API_04.Models;

public partial class Exhibit
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Artist { get; set; }

    public string TimePeriod { get; set; }

    public string Image { get; set; }

    public int ExhibitCategoryId { get; set; }

    public virtual ICollection<EventExhibit> EventExhibits { get; set; } = new List<EventExhibit>();

    public virtual ExhibitCategory ExhibitCategory { get; set; }

    public virtual ICollection<ExhibitTag> ExhibitTags { get; set; } = new List<ExhibitTag>();
}