//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventBanner
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string Banner { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
