//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibit
    {
        public Exhibit()
        {
            this.EventExhibits = new HashSet<EventExhibit>();
            this.ExhibitTags = new HashSet<ExhibitTag>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string TimePeriod { get; set; }
        public string Image { get; set; }
        public int ExhibitCategoryID { get; set; }
    
        public virtual ICollection<EventExhibit> EventExhibits { get; set; }
        public virtual ExhibitCategory ExhibitCategory { get; set; }
        public virtual ICollection<ExhibitTag> ExhibitTags { get; set; }
    }
}
