//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBCAEntities : DbContext
    {
        public MBCAEntities()
            : base("name=MBCAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<EventBanner> EventBanners { get; set; }
        public DbSet<EventCategory> EventCategories { get; set; }
        public DbSet<EventExhibit> EventExhibits { get; set; }
        public DbSet<Exhibit> Exhibits { get; set; }
        public DbSet<ExhibitCategory> ExhibitCategories { get; set; }
        public DbSet<ExhibitTag> ExhibitTags { get; set; }
        public DbSet<OTP> OTPs { get; set; }
        public DbSet<PhonePrefix> PhonePrefixes { get; set; }
        public DbSet<Promo> Promoes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
