//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Code { get; set; }
        public byte[] ValidUntil { get; set; }
    
        public virtual User User { get; set; }
    }
}
