//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCA_Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int EventID { get; set; }
        public int UserID { get; set; }
        public int Qty { get; set; }
        public Nullable<int> PromoID { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Promo Promo { get; set; }
        public virtual User User { get; set; }
    }
}
