//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esemka_Vote
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingDetail
    {
        public int Id { get; set; }
        public int VotedCandidateId { get; set; }
        public int EmployeeId { get; set; }
        public string Reason { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual VotingCandidate VotingCandidate { get; set; }
    }
}
