//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovSedhep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int TransactionID { get; set; }
        public int TableID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual RestaurantTable RestaurantTable { get; set; }
    }
}
